### ISSUE TITLE
Feature Request：文件类型默认包含 tsx

### ISSUE THREAD

**Issue by fool2fish** [xudeming208/file-stats#3]
### 问题是什么
默认文件类型不包含 tsx，但 tsx 是现在比较常见的文件类型，如果需要纳入统计就需要自己写一遍所有要统计的文件类型

**Comment by xudeming208** [comment]
> ### 问题是什么
> 默认文件类型不包含 tsx，但 tsx 是现在比较常见的文件类型，如果需要纳入统计就需要自己写一遍所有要统计的文件类型

感谢反馈。已经在2.2.14版本中增加了jsx、tsx的统计。
